version: '3'
services:
  nginx:
    build: ./build/nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
      - ./repository:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php7
      - php5
      - php8
    networks:
      default:
        aliases:
          - phpinfo5.test
          - phpinfo7.test
          - phpinfo8.test

  php8:
    build: ./build/php8
    volumes:
      - ./repository:/var/www/html

  php7:
    build: ./build/php7
    volumes:
      - ./repository:/var/www/html

  php5:
    build: ./build/php5
    volumes:
      - ./config/php-fpm.d/5.www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./repository:/var/www/html

  node:
    build: ./build/node
    working_dir: /var/www/html
    volumes:
      - ./repository:/var/www/html
    tty: true

  mariadb:
    build: ./build/mariadb
    volumes:
      - ./database:/var/lib/mysql
      - ./repository:/var/www/html
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks: 
      - default

  memcached:
    build: ./build/memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_MAX_CONNECTIONS=2000
      - MEMCACHED_THREADS=4
    ports:
      - 11211:11211
    networks:
      - default

  phpmyadmin:
    build: ./build/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - default

  mailhog:
    build: ./build/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - default

networks:
  default:
    driver: bridge
